### ISSUE TITLE
System.text.Json should only be included for net standard

### ISSUE THREAD

**Issue by thompson-tomo** [vpekarek/InterfaceConverter.SystemTextJson#5]
**Is your feature request related to a problem? Please describe.**
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

**Describe the solution you'd like**
I want the package to not have an explicit dependency on System.Text.Json as it can be provided by the framework when targeting net 6. 

**Describe alternatives you've considered**
Accept the additional dependency

**Additional context**
n/a

**Comment by vpekarek** [comment]
If you have _System.Text.Json_ package installed, it will use the same version you have. It should not download it again.
I just published new version [1.3.0](https://www.nuget.org/packages/InterfaceConverter.SystemTextJson/1.3.0) where the dependency is 6.0 or greater.

Will this help?
The package has to specify the reference to this package, because it can't be used without it.

Is this version helping you to achieve what you need?

**Comment by thompson-tomo** [comment]
If the framework is able to provide the library then it doesn't need to be explicitly added which is the case here for none net standard targets.

**Comment by vpekarek** [comment]
Can you try version [1.3.1](https://www.nuget.org/packages/InterfaceConverter.SystemTextJson/1.3.1)? This version should have limited dependency only for netstandard2.0 & 2.1
